### ISSUE TITLE
ArrayIndexOutOfBoundsException when analyzing repo

### ISSUE THREAD

**Issue by damithc** [se-edu/RepoSense#53]
I get this when I try to analyze markbind/markbind repo. Possibly because there are no java files?

>analyzing commits for markbind/markbind...
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
        at git.GitLogger.parseCommitInfo(GitLogger.java:35)
        at git.GitLogger.getCommits(GitLogger.java:27)
        at analyzer.RepoAnalyzer.analyzeCommits(RepoAnalyzer.java:20)
        at report.RepoInfoFileGenerator.analyzeRepos(RepoInfoFileGenerator.java:52)
        at report.RepoInfoFileGenerator.generateReposReport(RepoInfoFileGenerator.java:29)
        at frontend.Client.run(Client.java:54)
        at frontend.RepoSense.main(RepoSense.java:16)

**Comment by harryggg** [comment]
Can u provide the csv file here, thx!

**Comment by damithc** [comment]
I've modified the file since.
It had only one data row.

Organization | Repository | branch | Student1 Git ID | Student1 Display Name | Student1's Git Alias | Student2 Git ID | Student2 Display Name | Student2's Git Alias | Student3 Git ID | Student3 Display Name | Student3's Git Alias | Student4 Git ID | Student4 Display Name | Student4's Git   Alias
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
markbind | markbind | master | aaronjhchong[at]hotmail.com | Aaron |   |  |  |   |  |  |   |  |  |   |  

replace `[at]` with `@`

**Comment by harryggg** [comment]
Yes. It is because there is no Java/adoc....Configurable file extension should be a easy feature to implement

**Comment by harryggg** [comment]
anyway, there shouldnt be an exception thrown. Fixing.
